// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package user

import (
	"database/sql"
)

type User struct {
	ID        int32        `json:"id"`
	Email     string       `json:"email"`
	Username  string       `json:"username"`
	Password  string       `json:"password"`
	CreatedAt sql.NullTime `json:"created_at"`
}
